version: '3.1'

services:

  db_webflux:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: isac
      POSTGRES_PASSWORD: admin

